"use client";
import { useState } from "react";
import { Download, X } from "lucide-react";
export default function DownloadProjectButton({slug,title}:{slug:string;title:string}){
 const [open,setOpen]=useState(false);const[email,setEmail]=useState("");const[otp,setOtp]=useState("");const[id,setId]=useState<number|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
 const request=async()=>{setError("");setMessage("");if(!email.includes("@")){setError("Enter a valid email address.");return;}try{setBusy(true);const r=await fetch("/api/project-download/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,email})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to send verification code.");setId(Number(d.id));setMessage("Verification code sent to your email.");}catch(e){setError(e instanceof Error?e.message:"Unable to send code.");}finally{setBusy(false)}};
 const verify=async()=>{setError("");if(!id||!/^[0-9]{6}$/.test(otp)){setError("Enter the 6-digit code.");return;}try{setBusy(true);const r=await fetch("/api/project-download/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,otp})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Verification failed.");window.location.href=d.downloadUrl;setOpen(false);}catch(e){setError(e instanceof Error?e.message:"Verification failed.");}finally{setBusy(false)}};
 return <>{open&&<div className="premium-modal-backdrop"><div className="premium-modal"><button className="modal-close" onClick={()=>setOpen(false)}><X/></button><div className="modal-icon"><Download/></div><span className="eyebrow">VERIFIED PROJECT DOWNLOAD</span><h3>{title}</h3>{!id?<><p>Enter your email. A verification code is mandatory before the project file can be downloaded.</p><input className="premium-modal-input" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com"/></>:<><p>Enter the 6-digit code sent to <strong>{email}</strong>.</p><input className="otp-input-premium" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" placeholder="000000"/></>}{error&&<div className="form-message form-error">{error}</div>}{message&&<div className="form-message form-success">{message}</div>}<button className="contact-submit" disabled={busy} onClick={id?verify:request}>{busy?"Please wait…":id?"Verify & download":"Send verification code"}</button></div></div>}<button className="case-download-btn" onClick={()=>{setOpen(true);setError("");setMessage("");}} data-analytics="project_download_request"><Download size={17}/> Download project files</button></>;
}
